# Generated by Django 4.2.1 on 2023-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditii',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='termini',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
