# Generated by Django 4.2.1 on 2023-12-11 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_datecontact_linguriretele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditii',
            name='descrierea',
        ),
        migrations.CreateModel(
            name='Descriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrierea', models.TextField()),
                ('conditi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.conditii')),
            ],
        ),
    ]
