# Generated by Django 4.2.1 on 2023-12-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_rename_descriere_descrierii'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Descrierii',
        ),
    ]
