# Generated by Django 4.2.1 on 2023-12-11 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_delete_descrierii'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descrierii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrierea', models.TextField()),
                ('conditi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.conditii')),
            ],
        ),
    ]
