# Generated by Django 4.2.1 on 2023-12-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_about_detalii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalii',
            name='about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about.about'),
        ),
    ]
