# Generated by Django 4.2.1 on 2023-12-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_detalii_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalii',
            name='about',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='about.about'),
            preserve_default=False,
        ),
    ]
