# Generated by Django 4.2.1 on 2023-12-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_detalii_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Despre',
        ),
        migrations.RenameField(
            model_name='detalii',
            old_name='about',
            new_name='despre',
        ),
    ]
