version: '3'

services:
  frontend:
    image: frontend
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      django:
        condition: service_healthy

  django:
    image: backend
    build: Backend
    #    command: python Backend/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/Backend
    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "python", "manage.py", "migrate"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Backend/media:/Backend/media
      - ./Backend/static:/Backend/static
    depends_on:
      - django
      - frontend
    command: /bin/sh -c "nginx -t && nginx -g 'daemon off;'"

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: mariadb
      MARIADB_USER: root
      MARIADB_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data: