# Generated by Django 4.2.1 on 2023-10-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0006_produs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='capacitate_cilindrica',
        ),
    ]
