# Generated by Django 4.2.1 on 2023-10-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0009_produs_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='produs',
            name='images',
        ),
        migrations.AddField(
            model_name='produs',
            name='images',
            field=models.ManyToManyField(to='produs.myimage'),
        ),
    ]
