# Generated by Django 4.2.1 on 2023-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0010_myimage_remove_produs_images_produs_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.ImageField(upload_to='car/'),
        ),
    ]
