# Generated by Django 4.2.1 on 2023-10-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0011_alter_myimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='images',
        ),
    ]
