# Generated by Django 4.2.1 on 2023-10-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0012_remove_produs_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='images',
            field=models.ManyToManyField(to='produs.myimage'),
        ),
    ]
