# Generated by Django 4.2.1 on 2023-10-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0014_remove_produs_images_myimage_produs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyImage',
            new_name='Images',
        ),
    ]
