# Generated by Django 4.2.1 on 2023-10-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0015_rename_myimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produs',
            old_name='descriereae',
            new_name='descriere',
        ),
    ]
