# Generated by Django 4.2.1 on 2023-10-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0016_rename_descriereae_produs_descriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='car/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
