# Generated by Django 4.2.1 on 2023-12-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0018_remove_produs_image_produs_total_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicii',
        ),
        migrations.AddField(
            model_name='produs',
            name='price1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produs',
            name='price2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produs',
            name='price3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produs',
            name='price4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produs',
            name='price5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
