# Generated by Django 4.2.1 on 2024-01-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0020_alter_produs_limita_de_km_alter_produs_an'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='Limita_de_KM',
            field=models.CharField(default='fără limit', max_length=200),
        ),
    ]
