# Generated by Django 4.2.1 on 2024-01-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0021_alter_produs_limita_de_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='Limita_de_KM',
            field=models.CharField(default='fara limita', max_length=200),
        ),
    ]
