# Generated by Django 4.2.1 on 2024-02-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0024_alter_produs_capacitate_cilindrica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField()),
            ],
        ),
    ]
