# Generated by Django 4.2.1 on 2024-02-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0025_bbc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bbc',
        ),
    ]
