# Generated by Django 4.2.1 on 2024-02-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0027_rename_capacitate_cilindrica_produs_capacitate_cilindricaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produs',
            old_name='capacitate_cilindricaa',
            new_name='capacitate_cilindrica',
        ),
    ]
