# Generated by Django 4.2.1 on 2023-09-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profiles_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar/'),
        ),
    ]
