# Generated by Django 4.2.1 on 2023-09-06 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profiles_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
