# Generated by Django 4.2.1 on 2023-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_apartment_address_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
